version: "2"
services:
  kafka :
    image : spotify/kafka
    container_name : kafka
    network_mode : host
    ports :
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_PORT=9092

  eureka:
    build : ./discovery-service-eureka
    network_mode : host
    container_name : eureka
    ports :
      - "8020:8020"

  # db:
  #   image: mysql:latest
  #   container_name : mysql
  #    network_mode : host
  #   restart: always
  #   ports :
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD : mysql
  #     MYSQL_DATABASE : OAUTH

  ui : 
    build : ./UserUI
    network_mode : host
    ports : 
      - "4200:4200"

  # auth : 
  #   build : ./OAuthService
  #   network_mode : host
  #   ports :
  #     - "8087:8087"
  #   environment :
  #      mysql_url : mysql
  
  graph :
    image : neo4j
    container_name : neo4jgraph
    network_mode : host
    ports : 
      - "7474:7474"
      - "7687:7687"
    environment :
      - NEO4J_AUTH = none
      
  domainexpert : 
    build : ./domainexpert
    network_mode : host
    ports : 
      - "8089:8089"
    depends_on :
      - kafka
      - eureka
  
  googleapi :
    build : ./GoogleApi
    network_mode : host
    ports :
      - "8081:8081"
    depends_on :
      - kafka
      - eureka
  
  crawler : 
    build : ./Crawler
    network_mode : host
    ports :
      - "8070:8070"
    depends_on : 
      - kafka
      - eureka
  
  parser :
    build : ./Parser
    network_mode : host
    ports :
      - "8060:8060"
    depends_on :
      - kafka
      - eureka
  
  indexer :
    build : ./Semantic-Search-Index
    network_mode : host
    ports :
      - "8085:8085"
    depends_on :
      - kafka
      - eureka 
  
  conceptgraph :
    build : ./neo4j-concept
    network_mode : host
    ports :
      - "8095:8095"
    depends_on :
      - kafka
      - graph
      - eureka
  
  intentgraph :
    build : ./neo4j-intent
    network_mode : host
    ports :
      - "8096:8096"
    depends_on :
      - graph
      - kafka
      - eureka

  spellchecker :
    build : ./spell-checker
    network_mode : host
    ports :
      - "8051:8051"
    depends_on :
      - kafka
      - eureka
 
  pos_ner :
    build : ./nlp
    network_mode : host
    ports :
      - "8052:8052"
    depends_on :
      - kafka
      - eureka
 
  stopwords :
    build : ./StopWords
    network_mode : host
    ports :
      - "8053:8053"
    depends_on :
      - kafka
      - eureka
  
  lemmatizer :
    build : ./Lemmatizer
    network_mode : host
    ports :
      - "8054:8054"
    depends_on :
      - kafka
      - eureka
  
  intentsearch:
    build : ./IntentSearchService
    network_mode : host
    ports :
      - "8055:8055"
    depends_on :
      - kafka
      - eureka
      - graph

  stomp:
    build : ./stomp
    network_mode : host
    ports :
      - "8088:8088"
    depends_on :
      - kafka
      - eureka
